name: Validate PR Source Branches

on:
  # pull_request:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [stable, 'lts/**', 'v[0-9]+.[0-9]+.x', 'beta']

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check stable branch source
        if: github.base_ref == 'stable'
        run: |
          echo "Pull Request Source Branch: ${{ github.head_ref }}"
          echo "Pull Request Target Branch: ${{ github.base_ref }}"
          if [[ -z "${{ github.head_ref }}" =~ ^(beta|hotfix\/*)$ ]]; then
            echo "::error::Pull requests to the 'stable' branch are only allowed from the 'beta' or 'hotfix/*' branches."
            exit 1
          fi
      - name: Check maintenance branch source
        if: contains(fromJSON("['lts/**', 'v[0-9]+.[0-9]+.x']"), github.base_ref)
        run: |
          echo "Pull Request Source Branch: ${{ github.head_ref }}"
          echo "Pull Request Target Branch: ${{ github.base_ref }}"
          if [[ -z "${{ github.head_ref }}" =~ ^(fix|patch|hotfix)\/*$ ]]; then
            echo "::error::Pull requests to maintenance branchec are only allowed from 'patch/*' or 'hotfix/*' branches."
            exit 1
          fi
      - name: Check stable branch source
        if: github.base_ref == 'beta'
        run: |
          echo "Pull Request Source Branch: ${{ github.head_ref }}"
          echo "Pull Request Target Branch: ${{ github.base_ref }}"
          if [[ -z "${{ github.head_ref }}" =~ ^(feature|feat|fix|patch|chore)\/*$ ]]; then
            echo "::error::Pull requests to the 'beta' branch are only allowed from 'feature/*', 'patch/*', or 'hotfix/*' branches."
            exit 1
          fi
